
import type { Generator } from '@/lib/types';

export const initialGenerators: Record<string, Generator> = {
  timeAnchor: {
    id: 'timeAnchor',
    name: 'Temporal Anchor',
    description: 'Stabilizes a small point in time, slowly generating Chrono Shards.',
    icon: 'Anchor',
    baseCost: 10,
    costResource: 'points',
    costScale: 1.15,
    basePps: 1,
    producesResource: 'points',
    quantity: 0,
    artifactIds: ['artifact_time_crystal'],
    artifactDropRateFormula: 'log(quantity +1) / 20', // e.g. 20 purchases ~ log(21)/20 ~ 3/20 = 15%
  },
  manaWell: {
    id: 'manaWell',
    name: 'Mana Wellspring',
    description: 'A mystical well that slowly bubbles forth Mana Orbs.',
    icon: 'Disc3',
    baseCost: 50,
    costResource: 'points',
    costScale: 1.20,
    basePps: 0.5, // Produces 0.5 Mana Orbs per second
    producesResource: 'mana',
    quantity: 0,
  },
  goldMine: {
    id: 'goldMine',
    name: 'Ancient Gold Mine',
    description: 'Extracts flecks of ancient gold from the earth.',
    icon: 'Pickaxe',
    baseCost: 200,
    costResource: 'mana', // Costs Mana to operate
    costScale: 1.25,
    basePps: 0.1,
    producesResource: 'gold',
    quantity: 0,
    artifactIds: ['artifact_gold_nugget'],
    artifactDropRateFormula: 'log(quantity + 1) / 30',
  },
  libraryScrolls: {
    id: 'libraryScrolls',
    name: 'Library of Scrolls',
    description: 'Generates Temporal Dust through ancient texts.',
    icon: 'ScrollText',
    baseCost: 50,
    costResource: 'points',
    costScale: 1.18,
    basePps: 2,
    producesResource: 'temporalDust',
    quantity: 0,
  },
  essenceCollector: {
    id: 'essenceCollector',
    name: 'Ethereal Collector',
    description: 'Gathers faint ethereal essence from the surroundings.',
    icon: 'Feather',
    baseCost: 1000,
    costResource: 'points',
    costScale: 1.18,
    basePps: 1,
    producesResource: 'etherealEssence',
    quantity: 0,
  },
  filamentWeaver: {
    id: 'filamentWeaver',
    name: 'Cosmic Weaver',
    description: 'Spins raw cosmic energy into delicate filaments.',
    icon: 'Atom',
    baseCost: 500,
    costResource: 'temporalDust',
    costScale: 1.20,
    basePps: 0.5,
    producesResource: 'cosmicFilaments',
    quantity: 0,
  },
  voidMiner: {
    id: 'voidMiner',
    name: 'Void Miner',
    description: 'Extracts crystals from the edges of the void.',
    icon: 'Moon',
    baseCost: 200,
    costResource: 'etherealEssence',
    costScale: 1.22,
    basePps: 0.2,
    producesResource: 'voidCrystals',
    quantity: 0,
  },
  starcatcherNet: {
    id: 'starcatcherNet',
    name: 'Starlight Catcher',
    description: 'A celestial net that gathers falling starlight.',
    icon: 'Star',
    baseCost: 100,
    costResource: 'cosmicFilaments',
    costScale: 1.25,
    basePps: 0.1,
    producesResource: 'starlightShards',
    quantity: 0,
  },
  realityLoom: {
    id: 'realityLoom',
    name: 'Reality Loom',
    description: 'Weaves the very fabric of reality into tangible fibers.',
    icon: 'Spline',
    baseCost: 50,
    costResource: 'voidCrystals',
    costScale: 1.28,
    basePps: 0.05,
    producesResource: 'realityFibers',
    quantity: 0,
  },
  dreamcatcher: {
    id: 'dreamcatcher',
    name: 'Oneiric Catcher',
    description: 'Sifts through the dreamscape for coherent fragments.',
    icon: 'Cloud',
    baseCost: 250,
    costResource: 'starlightShards',
    costScale: 1.19,
    basePps: 0.8,
    producesResource: 'dreamFragments',
    quantity: 0,
  },
  echoChamber: {
    id: 'echoChamber',
    name: 'Echo Chamber',
    description: 'Amplifies faint memories into discernible echoes.',
    icon: 'AudioWaveform',
    baseCost: 150,
    costResource: 'dreamFragments',
    costScale: 1.21,
    basePps: 0.3,
    producesResource: 'memoryEchoes',
    quantity: 0,
  },
  catalyst9: {
    id: 'catalyst9',
    name: 'Catalyst Nine',
    description: 'A mysterious catalyst for Resource 9.',
    icon: 'FlaskConical',
    baseCost: 50000,
    costResource: 'points',
    costScale: 1.30,
    basePps: 0.02,
    producesResource: 'resource9',
    quantity: 0,
  },
  reactor10: {
    id: 'reactor10',
    name: 'Reactor Ten',
    description: 'A complex reactor for Resource 10.',
    icon: 'Radiation',
    baseCost: 1000,
    costResource: 'resource9',
    costScale: 1.32,
    basePps: 0.01,
    producesResource: 'resource10',
    quantity: 0,
  },
  synthesizer11: {
    id: 'synthesizer11',
    name: 'Synthesizer Eleven',
    description: 'Synthesizes Resource 11 from raw materials.',
    icon: 'Biohazard',
    baseCost: 500,
    costResource: 'resource10',
    costScale: 1.35,
    basePps: 0.005,
    producesResource: 'resource11',
    quantity: 0,
  },
  nexus12: {
    id: 'nexus12',
    name: 'Nexus Twelve',
    description: 'The ultimate nexus for Resource 12.',
    icon: 'Network',
    baseCost: 200,
    costResource: 'resource11',
    costScale: 1.40,
    basePps: 0.001,
    producesResource: 'resource12',
    quantity: 0,
  },
};
